name: github_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  graphql_flutter: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2
  mocktail: ^1.0.3
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - .env
